### ISSUE TITLE
R78 is too small

### ISSUE THREAD

**Issue by Zaaphod** [Smoothieware/Smoothieboard#8]
This is just a suggestion for a minor improvement to smoothieboard.  I recently hooked up my smoothieboard to a 24V power supply and noticed immediately that the red VBB led was so bright I could hardly see the nearby green led's 1-4

R78 is too small in comparison to the other current limiting resistors.  This is the current limiting resistor on the VBB LED10.  It's 2.2Kohms, but even at 12V the LED is extremely bright in comparison to the other LEDs,  and at 24V it's extremely bright.  The 2.2K resistor on LED 10 would make it draw 4.6mA at 12V and 10mA at 24V,  this is completely out or range of the other LEDs that draw only 1.5mA with their 1K current limiting resistors and 3.3V sources.

I noticed that other LEDs powered by VBB such as  LED5 - LED8 on the output FETs are 5.6K.  This is more in range if VBB=12V as the LED would be limited to 1.8mA  however at 24V it would still be overpowering at 4mA.
I would suggest 6.8Kohm - 10Kohm resistors for R78, and R65-R68 This would provide 1.5ma (6.8K) to 1mA (10K) at 12V and 3.3mA(6.8k) to 2.2mA(10k) at 24V - keeping these much more in range with the other LEDs.  Since I personally prefer 24V I would lean toward 10K, however even with 6.8K it would be much more in range of the other LEDs

Another option would be to make R78 5.6K and keep R65-R68 as is at 5.6K but then also reduce the size R10-R13 to 500-820ohms, this would make the green led's a little brighter. I would leave R77 alone because it's fine the way it is and is already brighter than the green LEDs

I realize this is a minor detail, but smoothie should be as good as it can be, and it's also a simple change to make.. no changes need to be made other than to change the resistor values.

Just for reference, I'm using 1.8v for the LED voltage drop and the formula  I=V-1.8/R  I don't know the exact specification of the LED's used

**Comment by logxen** [comment]
Yeah, this has actually been bothering me for quite a while. I should make all of the VBB based resistors match in the next board revision.

  Your suggestion of 10K is a nice compromise between the two standard voltages used. I want to avoid using that specific value though because it is potentially confusing. The value of 10K strongly implies that the part is a simple pull-up or pull-down. The nearest values in the 10% series are 8.2K and 12K. I think 8.2K would be a good choice. Any higher than 10K and I fear the VBB leds would appear visibly dim at 12V.

**Comment by Zaaphod** [comment]
I don't see what difference it makes whether it is the same value as a pull-up resistor, it's obviously in series with the LED.  However 8.2K would be way more balanced than the 2.2K resistor that is in there and be a big improvement.   If you wanted to stay away from 10K, then perhaps go with 8.2K for VBB resistors then decrease the green LED resistors to maybe 680ohms to help brighten the green LEDs a little.

**Comment by logxen** [comment]
Being addressed in v1.1
